// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAli0M4JnfoXt7IbHVPB-WAZzWp3C0ermQ',
    appId: '1:402143990077:web:08916fd90689449d98b554',
    messagingSenderId: '402143990077',
    projectId: 'metalfolding',
    authDomain: 'metalfolding.firebaseapp.com',
    storageBucket: 'metalfolding.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLdL58vN5eB5DWD9NnFldhmrcKdle4CoQ',
    appId: '1:402143990077:android:da1ad8f9bb9c87c398b554',
    messagingSenderId: '402143990077',
    projectId: 'metalfolding',
    storageBucket: 'metalfolding.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpS1_w5LS7xyQuWQjSSRlKaqy7Yo9X3c',
    appId: '1:402143990077:ios:5bc25c34ce7a725098b554',
    messagingSenderId: '402143990077',
    projectId: 'metalfolding',
    storageBucket: 'metalfolding.appspot.com',
    iosClientId: '402143990077-2tbaaueh0fh17vn3o29s86s772lgegep.apps.googleusercontent.com',
    iosBundleId: 'com.example.metalfolding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXpS1_w5LS7xyQuWQjSSRlKaqy7Yo9X3c',
    appId: '1:402143990077:ios:5bc25c34ce7a725098b554',
    messagingSenderId: '402143990077',
    projectId: 'metalfolding',
    storageBucket: 'metalfolding.appspot.com',
    iosClientId: '402143990077-2tbaaueh0fh17vn3o29s86s772lgegep.apps.googleusercontent.com',
    iosBundleId: 'com.example.metalfolding',
  );
}
